#!/bin/python3

import math
import os
import random
import re
import sys

def evaluate_number(n):
    if n % 2 != 0:
        print("Weird")
    else:
        if 2 <= n <= 5:
            print("Not Weird")
        elif 6 <= n <= 20:
            print("Weird")
        elif n > 20:
            print("Not Weird")

n = random.randint(0,20)
evaluate_number(n)
